### ISSUE TITLE
issues out the box

### ISSUE THREAD

**Issue by skyjamrey3** [CharlesBarone/bTimes#5]
Connecting to public(68.232.176.60:27015) ...
Server using 'friends' lobbies, requiring pw yes, lobby id ffffffffffffffff
Connecting to public(68.232.176.60:27015) ...
Server using 'friends' lobbies, requiring pw yes, lobby id ffffffffffffffff
Connected to 68.232.176.60:27015
just get that and my server stops after trying to load in

and ssj is broken as well:
3A3[4Timer3] 2- 5Jump: 41 5| PreSpeed: 4260
 3A3[4Timer3] 2- 5Jump: 42 5| Speed: 4360 5| Gain: 455.22%
 3A3[4Timer3] 2- 5Jump: 43 5| Speed: 4440 5| Gain: 464.90%

**Comment by CharlesBarone** [comment]
This seems odd, i linked my steam on the alliedmods post, if you add me there, i could possibly look at the server to help you diagnose this issue. There are multiple people running latest release without a problem so I need to see it to understand the issue and help you further.

**Comment by skyjamrey3** [comment]
i tried adding you, my steam is sklm

**Comment by CharlesBarone** [comment]
Alright, i have 277 pending requests, so i generally check in the afternoon for comments lol. I’ll add you in a moment.

**Comment by e-slut** [comment]
Did you remove the SSJ by Alatraz? Had the same problem with SSJ.

**Comment by CharlesBarone** [comment]
Seems like it was a client sided issue, he changed his csgo font. After reverting his font it seems to be fixed.
